name: food_delivery
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  copy_with_extension: ^2.0.0
  font_awesome_flutter: ^9.2.0
  flutter_bloc: ^8.0.0
  hydrated_bloc: ^8.0.0
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  copy_with_extension_gen:

flutter:
  uses-material-design: true

  assets:
    - assets/images/